import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';
import { buildExternalReferenceTable } from './external-reference-table.js';

const committed = JSON.parse(
  readFileSync(
    join(dirname(fileURLToPath(import.meta.url)), '../data/external-property-references.json'),
    'utf8',
  ),
).oils;

/**
 * Reproducibility guard: `external-property-references.json` is a build output (the band table the
 * gate reads) but is regenerated by a standalone script, not by `build`/`validate`/CI. Without this
 * test, editing the vendored sources or the pooling logic would silently leave the committed table
 * stale. Both this guard and the build script call the SAME `buildExternalReferenceTable`, so any
 * drift fails here.
 */
describe('external-property-references.json is reproducible from its sources', () => {
  it('committed band table equals a fresh pool of the vendored sources', () => {
    expect(committed).toEqual(buildExternalReferenceTable());
  });
});
